/*
  async action types
  https://redux.js.org/docs/advanced/AsyncActions.html
*/

// routes
export const CHANGE_ROUTE = "CHANGE_ROUTE";

// teams
export const FETCH_TEAMS_REQUEST = "FETCH_TEAMS_REQUEST";
export const FETCH_TEAMS_SUCCESS = "FETCH_TEAMS_SUCCESS";
export const FETCH_TEAMS_FAILURE = "FETCH_TEAMS_FAILURE";

export const CREATE_TEAM_REQUEST = "CREATE_TEAM_REQUEST";
export const CREATE_TEAM_SUCCESS = "CREATE_TEAM_SUCCESS";
export const CREATE_TEAM_FAILURE = "CREATE_TEAM_FAILURE";

export const DELETE_TEAM_REQUEST = "DELETE_TEAM_REQUEST";
export const DELETE_TEAM_SUCCESS = "DELETE_TEAM_SUCCESS";
export const DELETE_TEAM_FAILURE = "DELETE_TEAM_FAILURE";

export const UPDATE_TEAMS = "UPDATE_TEAMS";

// export const UPDATE_TEAMS_REQUEST = "UPDATE_TEAMS_REQUEST";
// export const UPDATE_TEAMS_SUCCESS = "UPDATE_TEAMS_SUCCESS";
// export const UPDATE_TEAMS_FAILURE = "UPDATE_TEAMS_FAILURE";

// teams members
export const FETCH_TEAM_MEMBERS_REQUEST = "FETCH_TEAM_MEMBERS_REQUEST";
export const FETCH_TEAM_MEMBERS_SUCCESS = "FETCH_TEAM_MEMBERS_SUCCESS";
export const FETCH_TEAM_MEMBERS_FAILURE = "FETCH_TEAM_MEMBERS_FAILURE";

export const CREATE_TEAM_MEMBER_REQUEST = "CREATE_TEAM_MEMBER_REQUEST";
export const CREATE_TEAM_MEMBER_SUCCESS = "CREATE_TEAM_MEMBER_SUCCESS";
export const CREATE_TEAM_MEMBER_FAILURE = "CREATE_TEAM_MEMBER_FAILURE";

export const ADD_TEAM_MEMBER = "ADD_TEAM_MEMBER";
export const CHANGE_TEAM = "CHANGE_TEAM";

// roles
export const FETCH_ROLES_REQUEST = "FETCH_ROLES_REQUEST";
export const FETCH_ROLES_SUCCESS = "FETCH_ROLES_SUCCESS";
export const FETCH_ROLES_FAILURE = "FETCH_ROLES_FAILURE";